// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
// Package emailtmpl holds the email-specific Templ components and

// their render helpers. It is a sibling of the email package

// (internal/email) by Go's directory = package rule; the parent

// package imports this one to render emails.

//

// All HTML in this package is designed for email-client

// compatibility. The rules are stricter than for web pages:

//

//   - Layout uses <table> with role="presentation", cellpadding,

//     cellspacing, and border attributes. CSS flex/grid does not

//     work in Outlook (Word rendering engine) and is unreliable in

//     older mobile clients.

//   - Every visible style is inline (style="..."). <style> blocks

//     are stripped by Gmail and most other webmail clients.

//   - No JavaScript. No htmx. No external CSS or fonts loaded from

//     the network — recipients may have images off by default, and

//     any third-party request also leaks their open to the

//     tracker.

//   - MSO conditional comments wrap the table layout so Outlook

//     falls back to a fixed-width rendering when its CSS engine

//     is not used.

//   - Colors are hard-coded hex values. oklch() (used by the web

//     app) is not supported in most email clients.

//

// The plaintext part of each email is produced by sibling

// Go functions in render.go, not by templ — the plaintext path

// has none of the above constraints and templ would be overkill.

package emailtmpl

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// EmailLayout is the outer wrapper for every email the app sends.
// It enforces the email-client compatibility rules from the
// package docstring. Children are rendered inside a single
// centered card with a 1px border and 8px radius; preheader is
// the short summary shown next to the subject in the inbox
// preview (Gmail truncates it around 100 chars).
//
// The two <table> wrappers around the card exist because some
// Outlook builds ignore width on <table> but respect it on
// <td>. Wrapping twice gives the cell a width that survives
// the round-trip.
func EmailLayout(preheader string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta name=\"x-apple-disable-message-reformatting\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><title>Stren</title></head><body style=\"margin:0;padding:0;background-color:#f4f4f5;font-family:Inter,Helvetica,Arial,sans-serif;color:#27272a;-webkit-text-size-adjust:100%;\"><div style=\"display:none;font-size:1px;color:#f4f4f5;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(preheader)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/email/templates/layout.templ`, Line: 53, Col: 15}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"background-color:#f4f4f5;\"><tr><td align=\"center\" style=\"padding:24px 12px;\"><!--[if mso | IE]>\n\t\t\t\t\t\t<table role=\"presentation\" width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td>\n\t\t\t\t\t\t<![endif]--><table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"max-width:600px;background-color:#ffffff;border:1px solid #e4e4e7;border-radius:8px;overflow:hidden;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</table><!--[if mso | IE]>\n\t\t\t\t\t\t</td></tr></table>\n\t\t\t\t\t\t<![endif]--></td></tr></table></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
