// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package emailtmpl

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// WeightReminderEmail is the HTML body of the per-user "time to
// log your weight" reminder. It is the transactional counterpart
// to the push notification fired by the same reminder job, so
// the two share the same call-to-action: tap the button (or the
// push), land on /weight/new, log the reading, optionally upload
// a photo.
//
// The cadence is rendered into the title and the header blurb so
// a daily subscriber gets "Today's weigh-in" and a weekly
// subscriber gets "Sunday weigh-in" (etc.) — the same template
// serves every frequency, so adding a new cadence is a one-line
// change in reminderCadenceCopy rather than a new templ file.
//
// The baseURL is threaded through so a staging deployment sends
// an email that points at itself, not at production.
func WeightReminderEmail(name string, baseURL string, subject string, header string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = EmailHeader().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <div style=\"padding:24px 0 8px 0;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = EmailTitle(subject).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = EmailParagraph("Hi "+name+", it's time to log your weight.").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = EmailParagraph(reminderBodyBlurb(subject)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = EmailButton(baseURL+"/weight/new", reminderButtonLabel(subject)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = EmailDivider().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = EmailFooter(CurrentYear(), baseURL).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = EmailLayout(header).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// reminderBodyBlurb returns the second-paragraph blurb for the
// email. Pulled into a function (rather than inlined into the
// templ) so the cadence-specific copy lives next to the
// cadence-specific subject and button label in render.go. The
// caller passes the subject, not the cadence, so the templ
// component stays a dumb renderer.
func reminderBodyBlurb(subject string) string {
	switch subject {
	case "Sunday weigh-in reminder":
		return "A single entry a week is the most reliable way to spot a trend without making the scale a daily event. Tap below to add today's reading — and feel free to add a photo if you want to see your progress over time."
	case "Time to log your weight":
		return "A quick reading keeps your trend line honest. Tap below to add today's entry — and feel free to add a photo if you want to see your progress over time."
	}
	return "Tap below to add today's reading."
}

// reminderButtonLabel returns the call-to-action label that
// shows on the email's big button. Mirrors the cadence-specific
// phrasing so a daily user sees "Log today's weight" and a
// weekly user sees "Log this week's weight".
func reminderButtonLabel(subject string) string {
	switch subject {
	case "Sunday weigh-in reminder":
		return "Log this week's weight"
	case "Time to log your weight":
		return "Log today's weight"
	}
	return "Log your weight"
}

var _ = templruntime.GeneratedTemplate
