// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package timers

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"stren/internal/views"
)

func EMOMPage(data views.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full max-w-md\"><div id=\"emom-presets\" class=\"grid grid-cols-2 md:grid-cols-4 gap-4 mb-8\"><button type=\"button\" class=\"btn text-center\" onclick=\"startPresetEMOM(5)\">5 Rounds</button> <button type=\"button\" class=\"btn text-center\" onclick=\"startPresetEMOM(10)\">10 Rounds</button> <button type=\"button\" class=\"btn text-center\" onclick=\"startPresetEMOM(15)\">15 Rounds</button> <button type=\"button\" class=\"btn text-center\" onclick=\"startPresetEMOM(20)\">20 Rounds</button></div><div id=\"custom-rounds-section\" class=\"flex flex-col items-center gap-6\"><label for=\"custom-rounds\" class=\"text-sm text-muted-foreground\">Custom rounds (max 15)</label> <input type=\"number\" id=\"custom-rounds\" class=\"input w-32 text-center text-lg\" min=\"1\" max=\"15\" placeholder=\"10\"> <button type=\"button\" id=\"start-custom-btn\" class=\"btn\" onclick=\"startCustomEMOM()\">Start</button></div><div id=\"emom-display\" class=\"flex-col items-center justify-center mt-8 hidden\"><div class=\"text-4xl font-bold mb-4\" id=\"round-display\">Round 1/--</div><div class=\"text-8xl font-bold tabular-nums\" id=\"countdown-display\">0:60</div><div class=\"flex gap-4 mt-8\"><button type=\"button\" id=\"start-btn\" class=\"btn hidden\" onclick=\"startEMOM()\">Start</button> <button type=\"button\" id=\"stop-btn\" class=\"btn-outline hidden\" onclick=\"stopEMOM()\">Stop</button> <button type=\"button\" id=\"reset-btn\" class=\"btn-outline hidden\" onclick=\"resetEMOM()\">Reset</button></div></div><div id=\"emom-complete\" class=\"flex-col items-center gap-4 mt-8 hidden\"><div class=\"text-4xl font-bold text-primary\">Complete!</div><button type=\"button\" class=\"btn-outline\" onclick=\"resetEMOM()\">Start Another</button></div></div><script src=\"/js/wake-lock.js\"></script> <script src=\"/js/emom.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = TimersLayout(data, "emom").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
