// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package timers

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"stren/internal/views"
)

func TimerPage(data views.PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full max-w-md\"><div id=\"timer-presets\" class=\"grid grid-cols-1 md:grid-cols-3 gap-4 mb-8\"><button type=\"button\" class=\"btn text-center\" onclick=\"startPresetTimer(30)\">30s</button> <button type=\"button\" class=\"btn text-center\" onclick=\"startPresetTimer(60)\">60s</button> <button type=\"button\" class=\"btn text-center\" onclick=\"startPresetTimer(90)\">90s</button></div><div id=\"custom-duration-section\" class=\"flex flex-col items-center gap-6\"><label for=\"custom-duration\" class=\"text-sm text-muted-foreground\">Custom duration (seconds)</label> <input type=\"number\" id=\"custom-duration\" class=\"input w-32 text-center text-lg\" min=\"1\" max=\"300\" placeholder=\"30\"> <button type=\"button\" id=\"start-custom-btn\" class=\"btn\" onclick=\"startCustomTimer()\">Start</button></div><div id=\"timer-display\" class=\"flex-col items-center justify-center mt-8\"><div class=\"text-8xl font-bold tabular-nums hidden\" id=\"countdown-display\">--:--</div><div class=\"flex gap-4 mt-8\"><button type=\"button\" id=\"start-btn\" class=\"btn hidden\" onclick=\"startTimer()\">Start</button> <button type=\"button\" id=\"stop-btn\" class=\"btn-outline hidden\" onclick=\"stopTimer()\">Stop</button> <button type=\"button\" id=\"reset-btn\" class=\"btn-outline hidden\" onclick=\"resetTimer()\">Reset</button></div></div><div id=\"timer-complete\" class=\"flex-col items-center gap-4 mt-8 hidden\"><div class=\"text-4xl font-bold text-primary\">Timer Complete!</div><button type=\"button\" class=\"btn-outline\" onclick=\"resetTimer()\">Start Another</button></div></div><script src=\"/js/wake-lock.js\"></script> <script src=\"/js/timer.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = TimersLayout(data, "timer").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
