// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_tokens.sql

package db

import (
	"context"
	"time"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :one
UPDATE auth_tokens
SET used_at = datetime('now')
WHERE token_hash = ?
  AND purpose = ?
  AND used_at IS NULL
  AND expires_at > datetime('now')
RETURNING id, user_id, purpose, token_hash, expires_at, used_at, created_at
`

type ConsumeAuthTokenParams struct {
	TokenHash string
	Purpose   string
}

// Atomically claim a token: marks used_at and returns the row only
// when the token exists for the given purpose, has not been used,
// and has not expired. The single-statement UPDATE...RETURNING is
// the concurrency primitive that prevents double-use across tabs,
// devices, or racing requests.
//
// `expires_at` comparison uses the literal `datetime('now')` rather
// than a parameter so the database clock (not the application clock)
// decides what "expired" means. SQLite's datetime('now') returns
// UTC, matching the value written by the application.
func (q *Queries) ConsumeAuthToken(ctx context.Context, arg ConsumeAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, consumeAuthToken, arg.TokenHash, arg.Purpose)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO auth_tokens (id, user_id, purpose, token_hash, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, purpose, token_hash, expires_at, used_at, created_at
`

type CreateAuthTokenParams struct {
	ID        string
	UserID    string
	Purpose   string
	TokenHash string
	ExpiresAt time.Time
}

// Insert a new auth token row. The caller is responsible for hashing
// the raw token with sha256 before storing. The raw token only ever
// lives in the email link; the database never sees it.
func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, createAuthToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
