// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exercises.sql

package db

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :one
INSERT INTO exercises (id, name, description, video_url, img_url, img_url_original, type)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateParams struct {
	ID             string
	Name           string
	Description    sql.NullString
	VideoUrl       sql.NullString
	ImgUrl         sql.NullString
	ImgUrlOriginal sql.NullString
	Type           string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.VideoUrl,
		arg.ImgUrl,
		arg.ImgUrlOriginal,
		arg.Type,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getByID = `-- name: GetByID :one
SELECT id, name, description, video_url, img_url, img_url_original, type
FROM exercises
WHERE id = ?
`

func (q *Queries) GetByID(ctx context.Context, id string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.VideoUrl,
		&i.ImgUrl,
		&i.ImgUrlOriginal,
		&i.Type,
	)
	return i, err
}

const getByName = `-- name: GetByName :one
SELECT id, name, description, video_url, img_url, img_url_original, type
FROM exercises
WHERE name = ?
`

func (q *Queries) GetByName(ctx context.Context, name string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getByName, name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.VideoUrl,
		&i.ImgUrl,
		&i.ImgUrlOriginal,
		&i.Type,
	)
	return i, err
}

const list = `-- name: List :many
SELECT id, name, description, video_url, img_url, img_url_original, type
FROM exercises
ORDER BY name
`

func (q *Queries) List(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.VideoUrl,
			&i.ImgUrl,
			&i.ImgUrlOriginal,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE exercises
SET name = ?, description = ?, video_url = ?, img_url = ?, img_url_original = ?, type = ?
WHERE id = ?
RETURNING id, name, description, video_url, img_url, img_url_original, type
`

type UpdateParams struct {
	Name           string
	Description    sql.NullString
	VideoUrl       sql.NullString
	ImgUrl         sql.NullString
	ImgUrlOriginal sql.NullString
	Type           string
	ID             string
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.Name,
		arg.Description,
		arg.VideoUrl,
		arg.ImgUrl,
		arg.ImgUrlOriginal,
		arg.Type,
		arg.ID,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.VideoUrl,
		&i.ImgUrl,
		&i.ImgUrlOriginal,
		&i.Type,
	)
	return i, err
}
