// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercise_types.sql

package db

import (
	"context"
)

const createType = `-- name: CreateType :one
INSERT INTO exercise_types (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=name
RETURNING id
`

func (q *Queries) CreateType(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createType, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTypeByName = `-- name: GetTypeByName :one
SELECT id, name
FROM exercise_types
WHERE name = ?
`

func (q *Queries) GetTypeByName(ctx context.Context, name string) (ExerciseType, error) {
	row := q.db.QueryRowContext(ctx, getTypeByName, name)
	var i ExerciseType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTypes = `-- name: ListTypes :many
SELECT id, name
FROM exercise_types
ORDER BY name
`

func (q *Queries) ListTypes(ctx context.Context) ([]ExerciseType, error) {
	rows, err := q.db.QueryContext(ctx, listTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseType
	for rows.Next() {
		var i ExerciseType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
