// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercises.sql

package db

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO exercises (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=name
RETURNING id
`

func (q *Queries) Create(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, create, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getByID = `-- name: GetByID :one
SELECT id, name
FROM exercises
WHERE id = ?
`

func (q *Queries) GetByID(ctx context.Context, id int64) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getByName = `-- name: GetByName :one
SELECT id, name
FROM exercises
WHERE name = ?
`

func (q *Queries) GetByName(ctx context.Context, name string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getByName, name)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const list = `-- name: List :many
SELECT id, name
FROM exercises
ORDER BY name
`

func (q *Queries) List(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE exercises
SET name = ?
WHERE id = ?
RETURNING id, name
`

type UpdateParams struct {
	Name string
	ID   int64
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, update, arg.Name, arg.ID)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
