// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercise_entries.sql

package db

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO exercise_entries (exercise_type_id, reps, weight, notes, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type CreateEntryParams struct {
	ExerciseTypeID int64
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.ExerciseTypeID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM exercise_entries WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const getEntriesByDateRange = `-- name: GetEntriesByDateRange :many
SELECT e.id, e.exercise_type_id, t.name as exercise_name, e.reps, e.weight, e.notes, e.created_at
FROM exercise_entries e
JOIN exercise_types t ON e.exercise_type_id = t.id
WHERE e.created_at BETWEEN ? AND ?
ORDER BY e.created_at DESC
`

type GetEntriesByDateRangeParams struct {
	FromCreatedAt sql.NullTime
	ToCreatedAt   sql.NullTime
}

type GetEntriesByDateRangeRow struct {
	ID             int64
	ExerciseTypeID int64
	ExerciseName   string
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) GetEntriesByDateRange(ctx context.Context, arg GetEntriesByDateRangeParams) ([]GetEntriesByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByDateRange, arg.FromCreatedAt, arg.ToCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesByDateRangeRow
	for rows.Next() {
		var i GetEntriesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseTypeID,
			&i.ExerciseName,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByExercise = `-- name: GetEntriesByExercise :many
SELECT e.id, e.exercise_type_id, t.name as exercise_name, e.reps, e.weight, e.notes, e.created_at
FROM exercise_entries e
JOIN exercise_types t ON e.exercise_type_id = t.id
WHERE t.name = ?
ORDER BY e.created_at DESC
`

type GetEntriesByExerciseRow struct {
	ID             int64
	ExerciseTypeID int64
	ExerciseName   string
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) GetEntriesByExercise(ctx context.Context, name string) ([]GetEntriesByExerciseRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByExercise, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesByExerciseRow
	for rows.Next() {
		var i GetEntriesByExerciseRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseTypeID,
			&i.ExerciseName,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT e.id, e.exercise_type_id, t.name as exercise_name, e.reps, e.weight, e.notes, e.created_at
FROM exercise_entries e
JOIN exercise_types t ON e.exercise_type_id = t.id
WHERE e.id = ?
`

type GetEntryRow struct {
	ID             int64
	ExerciseTypeID int64
	ExerciseName   string
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) GetEntry(ctx context.Context, id int64) (GetEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i GetEntryRow
	err := row.Scan(
		&i.ID,
		&i.ExerciseTypeID,
		&i.ExerciseName,
		&i.Reps,
		&i.Weight,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT e.id, e.exercise_type_id, t.name as exercise_name, e.reps, e.weight, e.notes, e.created_at
FROM exercise_entries e
JOIN exercise_types t ON e.exercise_type_id = t.id
ORDER BY e.created_at DESC
`

type ListEntriesRow struct {
	ID             int64
	ExerciseTypeID int64
	ExerciseName   string
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) ListEntries(ctx context.Context) ([]ListEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseTypeID,
			&i.ExerciseName,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesWithLimit = `-- name: ListEntriesWithLimit :many
SELECT e.id, e.exercise_type_id, t.name as exercise_name, e.reps, e.weight, e.notes, e.created_at
FROM exercise_entries e
JOIN exercise_types t ON e.exercise_type_id = t.id
ORDER BY e.created_at DESC
LIMIT ?
`

type ListEntriesWithLimitRow struct {
	ID             int64
	ExerciseTypeID int64
	ExerciseName   string
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) ListEntriesWithLimit(ctx context.Context, limit int64) ([]ListEntriesWithLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesWithLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesWithLimitRow
	for rows.Next() {
		var i ListEntriesWithLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseTypeID,
			&i.ExerciseName,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE exercise_entries
SET exercise_type_id = ?, reps = ?, weight = ?, notes = ?
WHERE id = ?
`

type UpdateEntryParams struct {
	ExerciseTypeID int64
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	ID             int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.ExerciseTypeID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateEntryWithDate = `-- name: UpdateEntryWithDate :exec
UPDATE exercise_entries
SET exercise_type_id = ?, reps = ?, weight = ?, notes = ?, created_at = ?
WHERE id = ?
`

type UpdateEntryWithDateParams struct {
	ExerciseTypeID int64
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	CreatedAt      sql.NullTime
	ID             int64
}

func (q *Queries) UpdateEntryWithDate(ctx context.Context, arg UpdateEntryWithDateParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryWithDate,
		arg.ExerciseTypeID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.CreatedAt,
		arg.ID,
	)
	return err
}
