// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exercise_entries.sql

package db

import (
	"context"
	"database/sql"
)

const createExerciseEntry = `-- name: CreateExerciseEntry :one
INSERT INTO exercise_entries (id, exercise_id, user_id, reps, weight, notes, rest_time, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateExerciseEntryParams struct {
	ID         string
	ExerciseID string
	UserID     sql.NullString
	Reps       int64
	Weight     float64
	Notes      sql.NullString
	RestTime   int64
	CreatedAt  sql.NullTime
}

func (q *Queries) CreateExerciseEntry(ctx context.Context, arg CreateExerciseEntryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createExerciseEntry,
		arg.ID,
		arg.ExerciseID,
		arg.UserID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.RestTime,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteExerciseEntry = `-- name: DeleteExerciseEntry :exec
DELETE FROM exercise_entries WHERE id = ? AND user_id = ?
`

type DeleteExerciseEntryParams struct {
	ID     string
	UserID sql.NullString
}

func (q *Queries) DeleteExerciseEntry(ctx context.Context, arg DeleteExerciseEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteExerciseEntry, arg.ID, arg.UserID)
	return err
}

const getExerciseEntriesByDateRange = `-- name: GetExerciseEntriesByDateRange :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.created_at BETWEEN ? AND ? AND e.user_id = ?
ORDER BY e.created_at DESC
`

type GetExerciseEntriesByDateRangeParams struct {
	CreatedAt   sql.NullTime
	CreatedAt_2 sql.NullTime
	UserID      sql.NullString
}

type GetExerciseEntriesByDateRangeRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) GetExerciseEntriesByDateRange(ctx context.Context, arg GetExerciseEntriesByDateRangeParams) ([]GetExerciseEntriesByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseEntriesByDateRange, arg.CreatedAt, arg.CreatedAt_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseEntriesByDateRangeRow
	for rows.Next() {
		var i GetExerciseEntriesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseEntriesByExercisePaginated = `-- name: GetExerciseEntriesByExercisePaginated :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.exercise_id = ? AND e.user_id = ?
ORDER BY e.created_at DESC
LIMIT ? OFFSET ?
`

type GetExerciseEntriesByExercisePaginatedParams struct {
	ExerciseID string
	UserID     sql.NullString
	Limit      int64
	Offset     int64
}

type GetExerciseEntriesByExercisePaginatedRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) GetExerciseEntriesByExercisePaginated(ctx context.Context, arg GetExerciseEntriesByExercisePaginatedParams) ([]GetExerciseEntriesByExercisePaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getExerciseEntriesByExercisePaginated,
		arg.ExerciseID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseEntriesByExercisePaginatedRow
	for rows.Next() {
		var i GetExerciseEntriesByExercisePaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseEntry = `-- name: GetExerciseEntry :one
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.id = ? AND e.user_id = ?
`

type GetExerciseEntryParams struct {
	ID     string
	UserID sql.NullString
}

type GetExerciseEntryRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) GetExerciseEntry(ctx context.Context, arg GetExerciseEntryParams) (GetExerciseEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getExerciseEntry, arg.ID, arg.UserID)
	var i GetExerciseEntryRow
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.UserID,
		&i.Reps,
		&i.Weight,
		&i.Notes,
		&i.RestTime,
		&i.CreatedAt,
	)
	return i, err
}

const getLastSetByExercise = `-- name: GetLastSetByExercise :one
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.exercise_id = ? AND e.user_id = ?
ORDER BY e.created_at DESC
LIMIT 1
`

type GetLastSetByExerciseParams struct {
	ExerciseID string
	UserID     sql.NullString
}

type GetLastSetByExerciseRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) GetLastSetByExercise(ctx context.Context, arg GetLastSetByExerciseParams) (GetLastSetByExerciseRow, error) {
	row := q.db.QueryRowContext(ctx, getLastSetByExercise, arg.ExerciseID, arg.UserID)
	var i GetLastSetByExerciseRow
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.UserID,
		&i.Reps,
		&i.Weight,
		&i.Notes,
		&i.RestTime,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxWeightByExercise = `-- name: GetMaxWeightByExercise :one
SELECT CAST(COALESCE(MAX(weight), 0) AS REAL) FROM exercise_entries
WHERE exercise_id = ? AND user_id = ?
`

type GetMaxWeightByExerciseParams struct {
	ExerciseID string
	UserID     sql.NullString
}

func (q *Queries) GetMaxWeightByExercise(ctx context.Context, arg GetMaxWeightByExerciseParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getMaxWeightByExercise, arg.ExerciseID, arg.UserID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const listExerciseEntries = `-- name: ListExerciseEntries :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.user_id = ?
ORDER BY e.created_at DESC
`

type ListExerciseEntriesRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) ListExerciseEntries(ctx context.Context, userID sql.NullString) ([]ListExerciseEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExerciseEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExerciseEntriesRow
	for rows.Next() {
		var i ListExerciseEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseEntriesLast7Days = `-- name: ListExerciseEntriesLast7Days :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.created_at >= datetime('now', '-7 days') AND e.user_id = ?
ORDER BY e.created_at DESC
`

type ListExerciseEntriesLast7DaysRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) ListExerciseEntriesLast7Days(ctx context.Context, userID sql.NullString) ([]ListExerciseEntriesLast7DaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listExerciseEntriesLast7Days, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExerciseEntriesLast7DaysRow
	for rows.Next() {
		var i ListExerciseEntriesLast7DaysRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseEntriesWithLimit = `-- name: ListExerciseEntriesWithLimit :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.user_id = ?
ORDER BY e.created_at DESC
LIMIT ?
`

type ListExerciseEntriesWithLimitParams struct {
	UserID sql.NullString
	Limit  int64
}

type ListExerciseEntriesWithLimitRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) ListExerciseEntriesWithLimit(ctx context.Context, arg ListExerciseEntriesWithLimitParams) ([]ListExerciseEntriesWithLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, listExerciseEntriesWithLimit, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExerciseEntriesWithLimitRow
	for rows.Next() {
		var i ListExerciseEntriesWithLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExerciseEntry = `-- name: UpdateExerciseEntry :exec
UPDATE exercise_entries
SET exercise_id = ?, reps = ?, weight = ?, notes = ?, rest_time = ?
WHERE id = ? AND user_id = ?
`

type UpdateExerciseEntryParams struct {
	ExerciseID string
	Reps       int64
	Weight     float64
	Notes      sql.NullString
	RestTime   int64
	ID         string
	UserID     sql.NullString
}

func (q *Queries) UpdateExerciseEntry(ctx context.Context, arg UpdateExerciseEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateExerciseEntry,
		arg.ExerciseID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.RestTime,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateExerciseEntryWithDate = `-- name: UpdateExerciseEntryWithDate :exec
UPDATE exercise_entries
SET exercise_id = ?, reps = ?, weight = ?, notes = ?, rest_time = ?, created_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateExerciseEntryWithDateParams struct {
	ExerciseID string
	Reps       int64
	Weight     float64
	Notes      sql.NullString
	RestTime   int64
	CreatedAt  sql.NullTime
	ID         string
	UserID     sql.NullString
}

func (q *Queries) UpdateExerciseEntryWithDate(ctx context.Context, arg UpdateExerciseEntryWithDateParams) error {
	_, err := q.db.ExecContext(ctx, updateExerciseEntryWithDate,
		arg.ExerciseID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.RestTime,
		arg.CreatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
