// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercise_entries.sql

package db

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO exercise_entries (id, exercise_id, user_id, reps, weight, notes, rest_time, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type CreateEntryParams struct {
	ID         string
	ExerciseID string
	UserID     sql.NullString
	Reps       int64
	Weight     float64
	Notes      sql.NullString
	RestTime   int64
	CreatedAt  sql.NullTime
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.ID,
		arg.ExerciseID,
		arg.UserID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.RestTime,
		arg.CreatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM exercise_entries WHERE id = ? AND user_id = ?
`

type DeleteEntryParams struct {
	ID     string
	UserID sql.NullString
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, arg.ID, arg.UserID)
	return err
}

const getEntriesByDateRange = `-- name: GetEntriesByDateRange :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.created_at BETWEEN ? AND ? AND e.user_id = ?
ORDER BY e.created_at DESC
`

type GetEntriesByDateRangeParams struct {
	CreatedAt   sql.NullTime
	CreatedAt_2 sql.NullTime
	UserID      sql.NullString
}

type GetEntriesByDateRangeRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) GetEntriesByDateRange(ctx context.Context, arg GetEntriesByDateRangeParams) ([]GetEntriesByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByDateRange, arg.CreatedAt, arg.CreatedAt_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesByDateRangeRow
	for rows.Next() {
		var i GetEntriesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByExercise = `-- name: GetEntriesByExercise :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE t.name = ? AND e.user_id = ?
ORDER BY e.created_at DESC
`

type GetEntriesByExerciseParams struct {
	Name   string
	UserID sql.NullString
}

type GetEntriesByExerciseRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) GetEntriesByExercise(ctx context.Context, arg GetEntriesByExerciseParams) ([]GetEntriesByExerciseRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByExercise, arg.Name, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesByExerciseRow
	for rows.Next() {
		var i GetEntriesByExerciseRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntry = `-- name: GetEntry :one
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.id = ? AND e.user_id = ?
`

type GetEntryParams struct {
	ID     string
	UserID sql.NullString
}

type GetEntryRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (GetEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getEntry, arg.ID, arg.UserID)
	var i GetEntryRow
	err := row.Scan(
		&i.ID,
		&i.ExerciseID,
		&i.ExerciseName,
		&i.UserID,
		&i.Reps,
		&i.Weight,
		&i.Notes,
		&i.RestTime,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.user_id = ?
ORDER BY e.created_at DESC
`

type ListEntriesRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) ListEntries(ctx context.Context, userID sql.NullString) ([]ListEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesLast30Days = `-- name: ListEntriesLast30Days :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.created_at >= datetime('now', '-30 days') AND e.user_id = ?
ORDER BY e.created_at DESC
`

type ListEntriesLast30DaysRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) ListEntriesLast30Days(ctx context.Context, userID sql.NullString) ([]ListEntriesLast30DaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesLast30Days, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesLast30DaysRow
	for rows.Next() {
		var i ListEntriesLast30DaysRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesWithLimit = `-- name: ListEntriesWithLimit :many
SELECT e.id, e.exercise_id, t.name as exercise_name, e.user_id, e.reps, e.weight, e.notes, e.rest_time, e.created_at
FROM exercise_entries e
JOIN exercises t ON e.exercise_id = t.id
WHERE e.user_id = ?
ORDER BY e.created_at DESC
LIMIT ?
`

type ListEntriesWithLimitParams struct {
	UserID sql.NullString
	Limit  int64
}

type ListEntriesWithLimitRow struct {
	ID           string
	ExerciseID   string
	ExerciseName string
	UserID       sql.NullString
	Reps         int64
	Weight       float64
	Notes        sql.NullString
	RestTime     int64
	CreatedAt    sql.NullTime
}

func (q *Queries) ListEntriesWithLimit(ctx context.Context, arg ListEntriesWithLimitParams) ([]ListEntriesWithLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesWithLimit, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesWithLimitRow
	for rows.Next() {
		var i ListEntriesWithLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.ExerciseID,
			&i.ExerciseName,
			&i.UserID,
			&i.Reps,
			&i.Weight,
			&i.Notes,
			&i.RestTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE exercise_entries
SET exercise_id = ?, reps = ?, weight = ?, notes = ?, rest_time = ?
WHERE id = ? AND user_id = ?
`

type UpdateEntryParams struct {
	ExerciseID string
	Reps       int64
	Weight     float64
	Notes      sql.NullString
	RestTime   int64
	ID         string
	UserID     sql.NullString
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.ExerciseID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.RestTime,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateEntryWithDate = `-- name: UpdateEntryWithDate :exec
UPDATE exercise_entries
SET exercise_id = ?, reps = ?, weight = ?, notes = ?, rest_time = ?, created_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateEntryWithDateParams struct {
	ExerciseID string
	Reps       int64
	Weight     float64
	Notes      sql.NullString
	RestTime   int64
	CreatedAt  sql.NullTime
	ID         string
	UserID     sql.NullString
}

func (q *Queries) UpdateEntryWithDate(ctx context.Context, arg UpdateEntryWithDateParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryWithDate,
		arg.ExerciseID,
		arg.Reps,
		arg.Weight,
		arg.Notes,
		arg.RestTime,
		arg.CreatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
