// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feedback.sql

package db

import (
	"context"
	"database/sql"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (id, user_id, title, message)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, title, message, is_closed, created_at, updated_at
`

type CreateFeedbackParams struct {
	ID      string
	UserID  string
	Title   string
	Message string
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, createFeedback,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Message,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT f.id, f.user_id, f.title, f.message, f.is_closed, f.created_at, f.updated_at, u.name as user_name
FROM feedback f
LEFT JOIN users u ON f.user_id = u.id
ORDER BY f.created_at DESC
`

type GetAllRow struct {
	ID        string
	UserID    string
	Title     string
	Message   string
	IsClosed  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserName  sql.NullString
}

func (q *Queries) GetAll(ctx context.Context) ([]GetAllRow, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllClosed = `-- name: GetAllClosed :many
SELECT f.id, f.user_id, f.title, f.message, f.is_closed, f.created_at, f.updated_at, u.name as user_name
FROM feedback f
LEFT JOIN users u ON f.user_id = u.id
WHERE f.is_closed = 1
ORDER BY f.created_at DESC
`

type GetAllClosedRow struct {
	ID        string
	UserID    string
	Title     string
	Message   string
	IsClosed  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserName  sql.NullString
}

func (q *Queries) GetAllClosed(ctx context.Context) ([]GetAllClosedRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllClosed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllClosedRow
	for rows.Next() {
		var i GetAllClosedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOpen = `-- name: GetAllOpen :many
SELECT f.id, f.user_id, f.title, f.message, f.is_closed, f.created_at, f.updated_at, u.name as user_name
FROM feedback f
LEFT JOIN users u ON f.user_id = u.id
WHERE f.is_closed = 0
ORDER BY f.created_at DESC
`

type GetAllOpenRow struct {
	ID        string
	UserID    string
	Title     string
	Message   string
	IsClosed  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserName  sql.NullString
}

func (q *Queries) GetAllOpen(ctx context.Context) ([]GetAllOpenRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOpen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOpenRow
	for rows.Next() {
		var i GetAllOpenRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbackByID = `-- name: GetFeedbackByID :one
SELECT f.id, f.user_id, f.title, f.message, f.is_closed, f.created_at, f.updated_at, u.name as user_name
FROM feedback f
LEFT JOIN users u ON f.user_id = u.id
WHERE f.id = ?
`

type GetFeedbackByIDRow struct {
	ID        string
	UserID    string
	Title     string
	Message   string
	IsClosed  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserName  sql.NullString
}

func (q *Queries) GetFeedbackByID(ctx context.Context, id string) (GetFeedbackByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedbackByID, id)
	var i GetFeedbackByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
	)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE feedback
SET is_closed = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, title, message, is_closed, created_at, updated_at
`

type UpdateStatusParams struct {
	IsClosed int64
	ID       string
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, updateStatus, arg.IsClosed, arg.ID)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
