// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, user_id, title, description, start_date, target_date, end_date, completed_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, title, description, start_date, target_date, end_date, completed_at, created_at, updated_at
`

type CreateGoalParams struct {
	ID          string
	UserID      string
	Title       string
	Description sql.NullString
	StartDate   sql.NullTime
	TargetDate  sql.NullTime
	EndDate     sql.NullTime
	CompletedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.TargetDate,
		arg.EndDate,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.TargetDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals
WHERE id = ? AND user_id = ?
`

type DeleteGoalParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.ExecContext(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT id, user_id, title, description, start_date, target_date, end_date, completed_at, created_at, updated_at FROM goals
WHERE id = ? AND user_id = ?
`

type GetGoalParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoal, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.StartDate,
		&i.TargetDate,
		&i.EndDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveGoals = `-- name: ListActiveGoals :many
SELECT id, user_id, title, description, start_date, target_date, end_date, completed_at, created_at, updated_at FROM goals
WHERE user_id = ? AND completed_at IS NULL
ORDER BY CASE WHEN target_date IS NULL THEN 1 ELSE 0 END, target_date ASC, created_at ASC
`

// Active goals: completed_at IS NULL. Order by target_date asc with nulls
// last, then by created_at asc as a stable tiebreaker. The CASE expression
// emulates NULLS LAST for SQLite versions that don't support it natively.
func (q *Queries) ListActiveGoals(ctx context.Context, userID string) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listActiveGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.TargetDate,
			&i.EndDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedGoals = `-- name: ListCompletedGoals :many
SELECT id, user_id, title, description, start_date, target_date, end_date, completed_at, created_at, updated_at FROM goals
WHERE user_id = ? AND completed_at IS NOT NULL
ORDER BY completed_at DESC
`

// Completed goals: completed_at IS NOT NULL. Most recently completed first.
func (q *Queries) ListCompletedGoals(ctx context.Context, userID string) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.StartDate,
			&i.TargetDate,
			&i.EndDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGoalComplete = `-- name: MarkGoalComplete :exec
UPDATE goals
SET completed_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND completed_at IS NULL
`

type MarkGoalCompleteParams struct {
	CompletedAt sql.NullTime
	ID          string
	UserID      string
}

// Atomically set completed_at and bump updated_at. Scoped to user_id so
// the request cannot mark another user's goal complete.
func (q *Queries) MarkGoalComplete(ctx context.Context, arg MarkGoalCompleteParams) error {
	_, err := q.db.ExecContext(ctx, markGoalComplete, arg.CompletedAt, arg.ID, arg.UserID)
	return err
}

const reopenGoal = `-- name: ReopenGoal :exec
UPDATE goals
SET completed_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type ReopenGoalParams struct {
	ID     string
	UserID string
}

// Atomically clear completed_at and bump updated_at. No-op if the goal
// is already active (completed_at is already NULL), so the route can
// call it without first checking the current state.
func (q *Queries) ReopenGoal(ctx context.Context, arg ReopenGoalParams) error {
	_, err := q.db.ExecContext(ctx, reopenGoal, arg.ID, arg.UserID)
	return err
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE goals
SET title = ?,
    description = ?,
    start_date = ?,
    target_date = ?,
    end_date = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateGoalParams struct {
	Title       string
	Description sql.NullString
	StartDate   sql.NullTime
	TargetDate  sql.NullTime
	EndDate     sql.NullTime
	ID          string
	UserID      string
}

// Update the editable fields. completed_at is managed by MarkGoalComplete
// and ReopenGoal (single-purpose methods that don't touch the rest of the
// row), so the edit form cannot accidentally clear or set the completed
// state. updated_at is bumped automatically.
func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.ExecContext(ctx, updateGoal,
		arg.Title,
		arg.Description,
		arg.StartDate,
		arg.TargetDate,
		arg.EndDate,
		arg.ID,
		arg.UserID,
	)
	return err
}
