// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AuthToken struct {
	ID        string
	UserID    string
	Purpose   string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}

type Exercise struct {
	ID             string
	Name           string
	Description    sql.NullString
	VideoUrl       sql.NullString
	ImgUrl         sql.NullString
	ImgUrlOriginal sql.NullString
	Type           string
}

type ExerciseEntry struct {
	ID         string
	ExerciseID string
	UserID     sql.NullString
	Reps       int64
	Weight     float64
	Notes      sql.NullString
	RestTime   int64
	CreatedAt  sql.NullTime
}

type Feedback struct {
	ID        string
	UserID    string
	Title     string
	Message   string
	IsClosed  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PushSubscription struct {
	ID         string
	UserID     string
	Endpoint   string
	P256dh     string
	Auth       string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

type User struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
	IsAdmin      int64
	TargetWeight sql.NullFloat64
	WeightUnit   string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type WeightEntry struct {
	ID        string
	UserID    string
	Weight    float64
	Notes     sql.NullString
	PhotoKey  sql.NullString
	CreatedAt time.Time
}
