// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Exercise struct {
	ID   string
	Name string
}

type ExerciseEntry struct {
	ID         string
	ExerciseID string
	UserID     sql.NullString
	Reps       int64
	Weight     float64
	Notes      sql.NullString
	CreatedAt  sql.NullTime
}

type Feedback struct {
	ID        string
	UserID    string
	Title     string
	Message   string
	IsClosed  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
	IsAdmin      int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
