// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type ExerciseEntry struct {
	ID             int64
	ExerciseTypeID int64
	UserID         sql.NullInt64
	Reps           int64
	Weight         float64
	Notes          sql.NullString
	CreatedAt      sql.NullTime
}

type ExerciseType struct {
	ID   int64
	Name string
}

type User struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
	IsAdmin      int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
