// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: push_subscriptions.sql

package db

import (
	"context"
)

const countPushSubscriptionsByUser = `-- name: CountPushSubscriptionsByUser :one
SELECT COUNT(*) FROM push_subscriptions WHERE user_id = ?
`

func (q *Queries) CountPushSubscriptionsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPushSubscriptionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPushSubscription = `-- name: CreatePushSubscription :one
INSERT INTO push_subscriptions (id, user_id, endpoint, p256dh, auth)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, endpoint, p256dh, auth, created_at, last_seen_at
`

type CreatePushSubscriptionParams struct {
	ID       string
	UserID   string
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, createPushSubscription,
		arg.ID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = ?
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const getPushSubscriptionByEndpoint = `-- name: GetPushSubscriptionByEndpoint :one
SELECT id, user_id, endpoint, p256dh, auth, created_at, last_seen_at
FROM push_subscriptions
WHERE endpoint = ?
`

func (q *Queries) GetPushSubscriptionByEndpoint(ctx context.Context, endpoint string) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, getPushSubscriptionByEndpoint, endpoint)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listAllPushSubscriptions = `-- name: ListAllPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth, created_at, last_seen_at
FROM push_subscriptions
`

func (q *Queries) ListAllPushSubscriptions(ctx context.Context) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listAllPushSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePushSubscription = `-- name: UpdatePushSubscription :one
UPDATE push_subscriptions
SET p256dh = ?, auth = ?, last_seen_at = CURRENT_TIMESTAMP
WHERE endpoint = ?
RETURNING id, user_id, endpoint, p256dh, auth, created_at, last_seen_at
`

type UpdatePushSubscriptionParams struct {
	P256dh   string
	Auth     string
	Endpoint string
}

func (q *Queries) UpdatePushSubscription(ctx context.Context, arg UpdatePushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, updatePushSubscription, arg.P256dh, arg.Auth, arg.Endpoint)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
