// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateEntry(ctx context.Context, arg CreateEntryParams) (int64, error)
	CreateType(ctx context.Context, name string) (int64, error)
	DeleteEntry(ctx context.Context, id int64) error
	GetEntriesByDateRange(ctx context.Context, arg GetEntriesByDateRangeParams) ([]GetEntriesByDateRangeRow, error)
	GetEntriesByExercise(ctx context.Context, name string) ([]GetEntriesByExerciseRow, error)
	GetEntry(ctx context.Context, id int64) (GetEntryRow, error)
	GetTypeByName(ctx context.Context, name string) (ExerciseType, error)
	ListEntries(ctx context.Context) ([]ListEntriesRow, error)
	ListEntriesWithLimit(ctx context.Context, limit int64) ([]ListEntriesWithLimitRow, error)
	ListTypes(ctx context.Context) ([]ExerciseType, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) error
	UpdateEntryWithDate(ctx context.Context, arg UpdateEntryWithDateParams) error
}

var _ Querier = (*Queries)(nil)
