// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weight_entries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWeightEntry = `-- name: CreateWeightEntry :one
INSERT INTO weight_entries (id, user_id, weight, notes, photo_key, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, weight, notes, photo_key, created_at
`

type CreateWeightEntryParams struct {
	ID        string
	UserID    string
	Weight    float64
	Notes     sql.NullString
	PhotoKey  sql.NullString
	CreatedAt time.Time
}

func (q *Queries) CreateWeightEntry(ctx context.Context, arg CreateWeightEntryParams) (WeightEntry, error) {
	row := q.db.QueryRowContext(ctx, createWeightEntry,
		arg.ID,
		arg.UserID,
		arg.Weight,
		arg.Notes,
		arg.PhotoKey,
		arg.CreatedAt,
	)
	var i WeightEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weight,
		&i.Notes,
		&i.PhotoKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWeightEntry = `-- name: DeleteWeightEntry :exec
DELETE FROM weight_entries
WHERE id = ? AND user_id = ?
`

type DeleteWeightEntryParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteWeightEntry(ctx context.Context, arg DeleteWeightEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteWeightEntry, arg.ID, arg.UserID)
	return err
}

const getWeightEntriesByIDs = `-- name: GetWeightEntriesByIDs :many
SELECT id, user_id, weight, notes, photo_key, created_at FROM weight_entries
WHERE id IN (?, ?) AND user_id = ?
`

type GetWeightEntriesByIDsParams struct {
	ID     string
	ID_2   string
	UserID string
}

func (q *Queries) GetWeightEntriesByIDs(ctx context.Context, arg GetWeightEntriesByIDsParams) ([]WeightEntry, error) {
	rows, err := q.db.QueryContext(ctx, getWeightEntriesByIDs, arg.ID, arg.ID_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeightEntry
	for rows.Next() {
		var i WeightEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Weight,
			&i.Notes,
			&i.PhotoKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeightEntry = `-- name: GetWeightEntry :one
SELECT id, user_id, weight, notes, photo_key, created_at FROM weight_entries
WHERE id = ? AND user_id = ?
`

type GetWeightEntryParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetWeightEntry(ctx context.Context, arg GetWeightEntryParams) (WeightEntry, error) {
	row := q.db.QueryRowContext(ctx, getWeightEntry, arg.ID, arg.UserID)
	var i WeightEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Weight,
		&i.Notes,
		&i.PhotoKey,
		&i.CreatedAt,
	)
	return i, err
}

const listWeightEntries = `-- name: ListWeightEntries :many
SELECT id, user_id, weight, notes, photo_key, created_at FROM weight_entries
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListWeightEntries(ctx context.Context, userID string) ([]WeightEntry, error) {
	rows, err := q.db.QueryContext(ctx, listWeightEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeightEntry
	for rows.Next() {
		var i WeightEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Weight,
			&i.Notes,
			&i.PhotoKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWeightEntry = `-- name: UpdateWeightEntry :exec
UPDATE weight_entries
SET weight = ?, notes = ?, photo_key = ?, created_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateWeightEntryParams struct {
	Weight    float64
	Notes     sql.NullString
	PhotoKey  sql.NullString
	CreatedAt time.Time
	ID        string
	UserID    string
}

func (q *Queries) UpdateWeightEntry(ctx context.Context, arg UpdateWeightEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateWeightEntry,
		arg.Weight,
		arg.Notes,
		arg.PhotoKey,
		arg.CreatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
